[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello_solana = "Gfpdhj6NVVnbrUa8bUb8gYXsU999Pj7iuZUdzYvXkSvs"

[programs.devnet]
hello_solana = "Gfpdhj6NVVnbrUa8bUb8gYXsU999Pj7iuZUdzYvXkSvs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
